name: 'olist_mart'
version: '1.0.0'
profile: 'olist_mart'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  olist_mart:
    staging:
      +materialized: view
    dimension:
      +materialized: table
    facts:
      +materialized: incremental
    marts:
      +materialized: table
